builds:
- env:
  - CGO_ENABLED=0
  goos:
  - linux
  - darwin
  goarch:
  - amd64
dockers:
- image_templates:
  - 'totvslabs/prometheus-digitalocean-sd:{{ .Tag }}'
  - 'totvslabs/prometheus-digitalocean-sd:latest'
