[[constraint]]
  branch = "master"
  name = "github.com/prometheus/common"

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "gopkg.in/alecthomas/kingpin.v2"
  version = "2.2.6"
